### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by T1mey** [gregorwolf/pg-beershop#169]
Hi @gregorwolf ,

I just tested the authentication of my service and it is accessible without authentication.

I added the strategy as here:
https://github.com/gregorwolf/pg-beershop/blob/2f9a5e81408a749a4e806d43119e927325d48d34/package.json#L91

I assmed that even in SAP BAS a xsuaa auth is goint to be forced. But there no auth. is coiming up ( I confgured default-env.json and  xs-security.sjon).

`cds env list requires.uaa` is returnung undefined.

**Comment by gregorwolf** [comment]
Please have a look at the developer tools network tab when you open the app in an incognito window. You will see that you're authenticated via the SAP ID Service (https://accounts.sap.com).

**Comment by T1mey** [comment]
I can access my deployed application (btp) without any authentication. BTP is configured to our corp. IDP.
So if I open the URL of the CAP sev app it's not forcing me to authenticate.

**Comment by gregorwolf** [comment]
It's normal that this page is shown for the srv part of the CAP applications. Have you tried accessing one of the services? It should give you an access denied. If you want to disable that this page is shown Please check out [CAP Release Notes from January 2021](https://cap.cloud.sap/docs/releases/changelog/#january-2021) -> cds.server provides an option to switch off automatically generated index.html served at /: Do that in a custom server.js:

**Comment by T1mey** [comment]
The page is not really the problem. But my service is delivering data out of the db without auth.

**Comment by gregorwolf** [comment]
Can you replicate the issue with the pg-beershop project? You can try my deployment at https://07fc19abtrial-dev-pg-beershop-srv.cfapps.eu10.hana.ondemand.com/ and you will see that all entities are protected.

**Comment by gregorwolf** [comment]
You can only access via the Approuter at https://07fc19abtrial-dev-pg-beershop-app.cfapps.eu10.hana.ondemand.com (please not that due to this running on SAP BTP trial the endpoints will only work in the next hours.

**Comment by T1mey** [comment]
Hi @gregorwolf ,

you're right your SAPUI5 frontend is protected by the amanged app router, which routes the calls to the srv_api destination.
In my case this is protected as well.

BUT if you invoke the odata service with the direct URL (I do not know the URL for you account) is is unprotected.

**Comment by gregorwolf** [comment]
If you can replicate the issue with the pg-beershop app then send me a link to your deployment. You might use your SAP BTP Trial account to not share the corporate one.

**Comment by T1mey** [comment]
Can you copy the URL and open this in a private browser session ?

![image](https://user-images.githubusercontent.com/10464878/141089652-7a549470-a45e-483a-9afb-468441140741.png)

**Comment by gregorwolf** [comment]
I can't access your subaccount. How should I copy that?

**Comment by T1mey** [comment]
I meant in yours...

**Comment by gregorwolf** [comment]
![Screenshot 2021-11-10 at 11 28 16](https://user-images.githubusercontent.com/2639535/141096627-61cacf88-c447-4fd5-87c9-c17814792d3a.png)

**Comment by T1mey** [comment]
ok. Thanks a lot.... 
Have to check why this is not working for me.

**Comment by T1mey** [comment]
Ah I see my mistake... You're using an own approuter for you UI5 apps.

```
- name: pg-beershop-app
    type: nodejs
    path: app
    build-parameters:
      ignore: ["node_modules/"]
    parameters:
      memory: 256M
      disk-quota: 1024M
    requires:
     - name: pg-beershop-destination-service
     - name: pg-beershop-uaa
     - name: srv-api
       group: destinations
       properties:
          forwardAuthToken: true
          strictSSL: false
          name: srv_api
          url: ~{srv-url}
```

I'm deploying my apps to the html5 repo and I need now to protect my cap project with xsuaa. I thought a require to xsuaa service would be enough... but it isn't
